### ISSUE TITLE
Error when trying to decrypt pass from v23

### ISSUE THREAD

**Issue by 4r73m190r0s** [maaaaz/sqldeveloperpassworddecryptor#12]
When I run
```
python ".\sqldeveloperpassworddecryptor.py" -d <id> -p "<password>"
```
I get this outcome
```
sqldeveloperpassworddecryptor.py version 2.1

[+] encrypted password: <password>
[+] db.system.id value: <id>
Usage: sqldeveloperpassworddecryptor.py [options]
Version: 2.1

sqldeveloperpassworddecryptor.py: error: Error during decryption. Remember, for a v4 -> v19.1 password you need the "-o" option
```

Even when I use `-o` option, I get error:
```
Traceback (most recent call last):
  File "C:\Users\<user>\Downloads\sqldeveloperpassworddecryptor.py", line 148, in <module>
    main()
  File "C:\Users\<user>\Downloads\sqldeveloperpassworddecryptor.py", line 135, in main
    print("\n[+] decrypted password: %s" % decrypt_v4(options.encrypted_password, options.db_system_id_value))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\Downloads\sqldeveloperpassworddecryptor.py", line 81, in decrypt_v4
    decrypted = des_cbc_decrypt(encrypted_password, secret_key, iv)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\Downloads\sqldeveloperpassworddecryptor.py", line 62, in des_cbc_decrypt
    decrypted_password = unpad(crypter.decrypt(encrypted_password))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python311\Lib\site-packages\Cryptodome\Cipher\_mode_cbc.py", line 246, in decrypt
    raise ValueError("Data must be padded to %d byte boundary in CBC mode" % self.block_size)
ValueError: Data must be padded to 8 byte boundary in CBC mode
```

**Comment by Yako0** [comment]
Facing the same issue, any thoughts?

**Comment by Yako0** [comment]
found this link in the other issue, and it's working with me

https://github.com/maaaaz/sqldeveloperpassworddecryptor/blob/338a4e190879893cf793a0db4f75cfa04d5cbe4c/sqldeveloperpassworddecryptor.py
